data <- read.table(unz("exdata%2Fdata%2Fhousehold_power_consumption.zip", 
                       "household_power_consumption.txt"), sep = ";", header = TRUE )
dim(data)
head(data)
colnames(data)
class(data$Date)
data$Date<-as.Date(data$Date, format="%d/%m/%Y")
x<-subset(data, data$Date=="2007-02-01" | data$Date=="2007-02-02")
head(x)
dim(x)
x$Global_active_power<-as.numeric(x$Global_active_power)
DateTime<-paste(x$Date,x$Time)
x$DateTime <- as.POSIXct(DateTime)
x$Sub_metering_1<-as.numeric(x$Sub_metering_1)
x$Sub_metering_2<-as.numeric(x$Sub_metering_2)
x$Sub_metering_3<-as.numeric(x$Sub_metering_3)
plot(x$Sub_metering_1~x$DateTime, type="l", ylab="Energy sub metering", xlab="") 
lines(x$Sub_metering_2~x$DateTime, col="red")
lines(x$Sub_metering_3~x$DateTime, col="blue")
legend("topright",col=c("black","red","blue"),lwd=c(1,1,1), 
       c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), cex=0.8
       )
dev.copy(png, "plot3.png", width=480, height=480)
dev.off()
